name: banking_flutter_ui
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  intl: ^0.19.0
  google_fonts: 6.1.0
  mobkit_dashed_border: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  

  flutter_lints: ^2.0.0


flutter:
  fonts:
    - family: OCRB
      fonts:
        - asset: lib/app/common/fonts/ocrb.ttf


  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
